# Generated by Django 4.0.3 on 2022-04-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        ("quizs", "0001_initial"),
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="quizs.quiz",
            ),
        ),
    ]
