# Generated by Django 3.0.4 on 2020-04-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_question_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="category_temp", new_name="category",
        ),
    ]
