# Generated by Django 3.0.4 on 2020-04-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_quiz_publish"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionCategory",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="QuestionTag",
            new_name="Tag",
        ),
    ]
