# Generated by Django 3.0.4 on 2020-04-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_auto_20200420_1230"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("Nouvelle question", "Nouvelle question"),
                    ("En cours de validation", "En cours de validation"),
                    ("Validée", "Validée"),
                    ("Écartée", "Écartée"),
                ],
                default="Nouvelle question",
                help_text="Le statut de la question dans le workflow de validation",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (0, "Junior"),
                    (1, "Facile"),
                    (2, "Moyen"),
                    (3, "Difficile"),
                    (4, "Expert"),
                ],
                help_text="Le niveau de difficulté de la question",
            ),
        ),
    ]
