# Generated by Django 3.0.4 on 2020-04-24 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_question_validation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="validator",
            field=models.CharField(
                blank=True,
                help_text="La personne qui a validée la question",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="created",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                choices=[
                    (0, "Junior"),
                    (1, "Facile"),
                    (2, "Moyen"),
                    (3, "Difficile"),
                    (4, "Expert"),
                ],
                default=1,
                help_text="Le niveau de difficulté de la question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="updated",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
