# Generated by Django 3.0.4 on 2020-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_contribution_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="image_background_url",
            field=models.URLField(
                blank=True,
                help_text="Un lien vers une image pour illustrer le quiz",
                max_length=500,
            ),
        ),
    ]
