# Generated by Django 3.0.4 on 2020-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_quiz_image_background_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="added",
            field=models.DateField(
                blank=True, help_text="La date d'ajout de la question", null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateField(
                auto_now_add=True, help_text="La date de création de la catégorie"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="created",
            field=models.DateField(
                auto_now_add=True, help_text="La date de création de la question"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created",
            field=models.DateField(
                auto_now_add=True, help_text="La date de création du quiz"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created",
            field=models.DateField(
                auto_now_add=True, help_text="La date de création du tag"
            ),
        ),
    ]
