# Generated by Django 3.0.4 on 2020-05-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_question_answer_image_explanation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionstat",
            old_name="answer_choice",
            new_name="choice",
        ),
        migrations.AddField(
            model_name="question",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0, help_text="Le nombre de dislikes"),
        ),
        migrations.AddField(
            model_name="question",
            name="like_count",
            field=models.PositiveIntegerField(default=0, help_text="Le nombre de likes"),
        ),
        migrations.CreateModel(
            name="QuestionFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("like", "Positif"), ("dislike", "Négatif")],
                        default="like",
                        editable=False,
                        help_text="L'avis laissé sur la question",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("question", "Question"), ("quiz", "Quiz")],
                        default="question",
                        editable=False,
                        help_text="Le contexte dans lequel a été envoyé le feedback",
                        max_length=50,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="La date & heure de la réponse"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="api.Question",
                    ),
                ),
            ],
        ),
    ]
