# Generated by Django 3.0.4 on 2020-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_create_model_dailystat"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dailystat",
            constraint=models.UniqueConstraint(fields=("date",), name="unique stat date"),
        ),
    ]
