# Generated by Django 3.0.4 on 2020-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_create_model_quizfeedbackevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystat",
            name="quiz_feedback_count",
            field=models.PositiveIntegerField(default=0, help_text="Le nombre de feedbacks aux quizs"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0, help_text="Le nombre de dislikes"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="like_count",
            field=models.PositiveIntegerField(default=0, help_text="Le nombre de likes"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_correct",
            field=models.CharField(
                choices=[("a", "a"), ("b", "b"), ("c", "c"), ("d", "d")],
                help_text="a, b, c ou d",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="questionanswerevent",
            name="choice",
            field=models.CharField(
                choices=[("a", "a"), ("b", "b"), ("c", "c"), ("d", "d")],
                editable=False,
                help_text="La réponse choisie par l'internaute",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="questionfeedbackevent",
            name="created",
            field=models.DateTimeField(auto_now_add=True, help_text="La date & heure de l'avis"),
        ),
        migrations.AlterField(
            model_name="questionfeedbackevent",
            name="source",
            field=models.CharField(
                choices=[("question", "Question"), ("quiz", "Quiz")],
                default="question",
                editable=False,
                help_text="Le contexte dans lequel a été envoyé l'avis",
                max_length=50,
            ),
        ),
    ]
