# Generated by Django 3.0.4 on 2020-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_question_hint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("QCM", "Questionnaire à choix multiples"),
                    (
                        "QCM-RM",
                        "Questionnaire à choix multiples avec réponses multiples",
                    ),
                    ("VF", "Vrai ou Faux"),
                ],
                help_text="Le type de question (QCM, V/F, ...)",
                max_length=50,
            ),
        ),
    ]
