# Generated by Django 3.0.4 on 2020-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_update_question_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("A valider", "A valider"),
                    ("Validée", "Validée"),
                    ("Écartée", "Écartée"),
                ],
                default="Brouillon",
                help_text="Le statut de la question dans le workflow de validation",
                max_length=150,
            ),
        ),
    ]
