# Generated by Django 3.0.4 on 2020-07-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_auto_20200706_1839"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAggStat",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="agg_stats",
                        serialize=False,
                        to="api.Question",
                    ),
                ),
                (
                    "answer_count",
                    models.PositiveIntegerField(default=0, help_text="Le nombre de réponses"),
                ),
                (
                    "answer_success_count",
                    models.PositiveIntegerField(default=0, help_text="Le nombre de réponses correctes"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, help_text="Le nombre de likes"),
                ),
                (
                    "dislike_count",
                    models.PositiveIntegerField(default=0, help_text="Le nombre de dislikes"),
                ),
            ],
        ),
    ]
