# Generated by Django 3.0.4 on 2020-07-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_questionaggstat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer_count",
        ),
        migrations.RemoveField(
            model_name="question",
            name="answer_success_count",
        ),
        migrations.RemoveField(
            model_name="question",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="question",
            name="like_count",
        ),
    ]
