# Generated by Django 3.0.4 on 2020-07-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_cleanup_question_quiz_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="like_count",
        ),
    ]
