# Generated by Django 3.0.4 on 2020-08-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_cleanup_quiz_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Un ou plusieurs tags rattaché au quiz",
                related_name="quizzes",
                to="api.Tag",
            ),
        ),
    ]
