# Generated by Django 3.0.4 on 2020-09-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_question_additional_answer_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_option_a",
            field=models.CharField(
                blank=True, help_text="La réponse a", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_option_b",
            field=models.CharField(
                blank=True, help_text="La réponse b", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Une seule catégorie possible",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="api.Category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "a"),
                    ("b", "b"),
                    ("c", "c"),
                    ("d", "d"),
                    ("ab", "ab"),
                    ("ac", "ac"),
                    ("ad", "ad"),
                    ("bc", "bc"),
                    ("bd", "bd"),
                    ("cd", "cd"),
                    ("abc", "abc"),
                    ("abd", "abd"),
                    ("acd", "acd"),
                    ("bcd", "bcd"),
                    ("abcd", "abcd"),
                ],
                help_text="a, b, c ou d. ab, acd, abcd, etc si plusieurs réponses.",
                max_length=50,
            ),
        ),
    ]
