# Generated by Django 3.0.4 on 2020-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_question_fields_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("QCM", "Questionnaire à choix multiples"),
                    (
                        "QCM-RM",
                        "Questionnaire à choix multiples avec réponses multiples",
                    ),
                    ("VF", "Vrai ou Faux"),
                ],
                default="QCM",
                help_text="Le type de question (QCM, V/F, ...)",
                max_length=50,
            ),
        ),
    ]
