# Generated by Django 3.1.1 on 2020-09-23 10:03

from django.db import migrations, models

import stats.constants


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_auto_20200922_1258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystat",
            name="hour_split",
            field=models.JSONField(
                default=stats.constants.daily_stat_hour_split_jsonfield_default_value,
                help_text="Les statistiques par heure",
            ),
        ),
    ]
