# Generated by Django 3.1.1 on 2020-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_auto_20201119_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="difficulty_average",
            field=models.FloatField(
                default=0, help_text="La difficulté moyenne des questions"
            ),
        ),
    ]
