# Generated by Django 3.1.1 on 2020-11-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_quizanswerevent_question_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="publish",),
    ]
