# Generated by Django 3.1.1 on 2020-12-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_configuration_add_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="notion_contributions_last_exported",
            field=models.DateTimeField(
                blank=True,
                help_text="La dernière fois que les contributions exportées vers Notion",
                null=True,
            ),
        ),
    ]
