# Generated by Django 3.1.4 on 2021-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_configuration_application_open_source_code_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="spotlight",
            field=models.BooleanField(
                default=False, help_text="Le quiz est mis en avant"
            ),
        ),
    ]
