# Generated by Django 3.1.4 on 2021-01-11 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_quiz_spotlight"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                migrations.RunSQL(
                    sql="ALTER TABLE api_quiz_questions RENAME TO api_quizquestion",
                    reverse_sql="ALTER TABLE api_quizquestion RENAME TO api_quiz_questions",
                ),
                migrations.RunSQL(
                    sql="ALTER SEQUENCE api_quiz_questions_id_seq RENAME TO api_quizquestion_id_seq",
                    reverse_sql="ALTER SEQUENCE api_quizquestion_id_seq RENAME TO api_quiz_questions_id_seq",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="QuizQuestion",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="api.question",
                            ),
                        ),
                        (
                            "quiz",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="api.quiz",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="quiz",
                    name="questions",
                    field=models.ManyToManyField(
                        help_text="Les questions du quiz",
                        through="api.QuizQuestion",
                        to="api.Question",
                    ),
                ),
            ],
        )
    ]
