# Generated by Django 3.1.4 on 2021-01-11 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_quiz_questions_through_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizquestion", options={"ordering": ["quiz_id", "order"]},
        ),
    ]
