# Generated by Django 3.1.4 on 2021-01-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_quiz_questions_through_unique_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                help_text="Les questions du quiz",
                related_name="quizzes",
                through="api.QuizQuestion",
                to="api.Question",
            ),
        ),
    ]
