# Generated by Django 3.1.4 on 2021-01-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_quiz_questions_through_add_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="notion_questions_scope_5_last_imported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que les questions (lot 5) ont été importées depuis Notion",
                null=True,
            ),
        ),
    ]
