# Generated by Django 3.1.4 on 2021-01-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_configuration_application_frontend_ecoindex_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="has_audio",
            field=models.BooleanField(
                default=False, help_text="Le quiz a du contenu audio"
            ),
        ),
    ]
