# Generated by Django 3.1.4 on 2021-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_quiz_has_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_reading_recommendation",
            field=models.TextField(blank=True, help_text="Un livre pour aller plus loin"),
        ),
    ]
