# Generated by Django 3.1.4 on 2021-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_migrate_stats_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizrelationship",
            name="status",
            field=models.CharField(
                choices=[
                    ("suivant", "suivant"),
                    ("jumeau", "jumeau"),
                    ("similaire", "similaire"),
                    ("traduction", "traduction"),
                ],
                help_text="Le type de relation entre les deux quizs",
                max_length=50,
            ),
        ),
    ]
