# Generated by Django 3.2.4 on 2021-06-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0081_configuration_github_export_dates"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Configuration",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Configuration",
                    table="core_configuration",
                )
            ],
        ),
    ]
