# Generated by Django 4.0.3 on 2022-03-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_migrate_glossary_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.IntegerField(blank=True, help_text="Une seule catégorie possible", null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Category",
                ),
            ],
            # want to reuse the table, don't drop it
            database_operations=[
                migrations.AlterModelTable(
                    name="Category",
                    table="categories_category",
                )
            ],
        ),
    ]
