# Generated by Django 4.0.3 on 2022-03-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0092_question_tags_quiz_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="questions",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="relationships",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="tags",
        ),
        # migrations.AlterUniqueTogether(
        #     name='quizquestion',
        #     unique_together=None,
        # ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="question",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizrelationship",
            name="from_quiz",
        ),
        migrations.RemoveField(
            model_name="quizrelationship",
            name="to_quiz",
        ),
    ]
