# Generated by Django 4.0.3 on 2022-03-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0093_remove_quiz_questions_remove_quiz_relationships_and_more"),
        ("stats", "0006_alter_quizanswerevent_quiz_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
        migrations.DeleteModel(
            name="QuizRelationship",
        ),
    ]
