# Generated by Django 4.0.3 on 2022-03-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_delete_quiz_delete_quizquestion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.RemoveField(
            model_name="question",
            name="tags",
        ),
    ]
