# Generated by Django 4.0.3 on 2022-03-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0004_alter_quiz_questions_alter_quizquestion_question"),
        ("api", "0095_remove_question_category_remove_question_tags"),
        ("stats", "0007_alter_questionaggstat_question_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
