# Generated by Django 4.0.4 on 2022-04-29 17:28

from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=core.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("CONTRIBUTOR", "Contributeur"),
                        ("SUPER-CONTRIBUTOR", "Super Contributeur"),
                        ("ADMINISTRATOR", "Administrateur"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Rôles",
            ),
        ),
    ]
