# Generated by Django 4.2.5 on 2023-09-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_home_last_seen_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last seen date on page 'My space'"),
        ),
        migrations.AlterField(
            model_name="user",
            name="logs",
            field=models.JSONField(default=list, editable=False, verbose_name="Historical logs"),
        ),
    ]
