# Generated by Django 4.2.5 on 2023-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_profile_home_last_seen_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_comments_last_seen_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last seen date on page 'Comments on my content'"
            ),
        ),
    ]
