# Generated by Django 4.1a1 on 2022-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0014_alter_historicalquestion_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquestion",
            name="validation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
        ),
        migrations.AddField(
            model_name="question",
            name="validation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
        ),
    ]
