# Generated by Django 4.1.3 on 2022-12-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0016_alter_historicalquestion_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_audio",
            new_name="answer_audio_url",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_video",
            new_name="answer_video_url",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_audio",
            new_name="answer_audio_url",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_video",
            new_name="answer_video_url",
        ),
    ]
