# Generated by Django 4.1.5 on 2023-02-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0018_historicalquestion_answer_audio_url_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_reading_recommendation",
            new_name="answer_book_recommendation",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_image_explanation",
            new_name="answer_image_url_text",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_accessible_url",
            new_name="answer_source_accessible_url",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_accessible_url_text",
            new_name="answer_source_accessible_url_text",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_scientific_url",
            new_name="answer_source_scientific_url",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_scientific_url_text",
            new_name="answer_source_scientific_url_text",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_reading_recommendation",
            new_name="answer_book_recommendation",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_image_explanation",
            new_name="answer_image_url_text",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_accessible_url",
            new_name="answer_source_accessible_url",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_accessible_url_text",
            new_name="answer_source_accessible_url_text",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_scientific_url",
            new_name="answer_source_scientific_url",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_scientific_url_text",
            new_name="answer_source_scientific_url_text",
        ),
    ]
