# Generated by Django 4.1.5 on 2023-02-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0019_rename_answer_reading_recommendation_historicalquestion_answer_book_recommendation_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_option_a",
            new_name="answer_choice_a",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_option_b",
            new_name="answer_choice_b",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_option_c",
            new_name="answer_choice_c",
        ),
        migrations.RenameField(
            model_name="historicalquestion",
            old_name="answer_option_d",
            new_name="answer_choice_d",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_option_a",
            new_name="answer_choice_a",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_option_b",
            new_name="answer_choice_b",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_option_c",
            new_name="answer_choice_c",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_option_d",
            new_name="answer_choice_d",
        ),
    ]
