# Generated by Django 4.1.5 on 2023-02-16 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("categories", "0004_alter_category_created"),
        ("questions", "0020_rename_answer_option_a_historicalquestion_answer_choice_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_audio_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer audio explanation (link)"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_audio_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer audio explanation (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_book_recommendation",
            field=models.TextField(blank=True, verbose_name="Answer reading recommandation"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_choice_a",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer a"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_choice_b",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer b"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_choice_c",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer c"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_choice_d",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer d"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "a"),
                    ("b", "b"),
                    ("c", "c"),
                    ("d", "d"),
                    ("ab", "ab"),
                    ("ac", "ac"),
                    ("ad", "ad"),
                    ("bc", "bc"),
                    ("bd", "bd"),
                    ("cd", "cd"),
                    ("abc", "abc"),
                    ("abd", "abd"),
                    ("acd", "acd"),
                    ("bcd", "bcd"),
                    ("abcd", "abcd"),
                ],
                help_text="a, b, c ou d (ab, acd, abcd… if multiple answers)",
                max_length=50,
                verbose_name="The correct answer",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_explanation",
            field=models.TextField(blank=True, verbose_name="Answer explanation"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_extra_info",
            field=models.TextField(
                blank=True, help_text="Won't be displayed in the application", verbose_name="Answer extra info"
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_image_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer image (link)"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_image_url_text",
            field=models.TextField(
                blank=True,
                help_text="Caption, translation, short explanation…",
                verbose_name="Answer image (text to display)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_source_accessible_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer accessible source (link)"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_source_accessible_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer accessible source (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_source_scientific_url",
            field=models.URLField(
                blank=True,
                help_text="Report, scientific article…",
                max_length=500,
                verbose_name="Answer scientific source (link)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_source_scientific_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer scientific source (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_video_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer video explanation (link)"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="answer_video_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer video explanation (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="author_string",
            field=models.CharField(blank=True, max_length=300, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="categories.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="category_string",
            field=models.CharField(blank=True, max_length=50, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="difficulty",
            field=models.IntegerField(
                choices=[(0, "Junior"), (1, "Facile"), (2, "Moyen"), (3, "Difficile"), (4, "Expert")],
                default=1,
                verbose_name="Difficulty level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="has_ordered_answers",
            field=models.BooleanField(
                default=True,
                help_text="True if the answer choices should be displayed in this particular order (instead of being mixed up)",
                verbose_name="Ordered answers?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="hint",
            field=models.TextField(
                blank=True, help_text="Text that the user can decide to display to help him", verbose_name="Hint"
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="language",
            field=models.CharField(
                choices=[("Français", "Français"), ("English", "English"), ("Deutsch", "Deutsch")],
                default="Français",
                max_length=50,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="text",
            field=models.TextField(help_text="Keep it simple", verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="updated",
            field=models.DateTimeField(blank=True, editable=False, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="validation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Validation date"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("A valider", "A valider"),
                    ("Validée", "Validée"),
                    ("Écartée temporairement", "Écartée temporairement"),
                    ("Écartée", "Écartée"),
                ],
                default="Brouillon",
                max_length=150,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validator",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="validator_string",
            field=models.CharField(blank=True, max_length=300, verbose_name="Validator"),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Publique (dans l'export et dans l'application)"),
                    ("HIDDEN", "Caché (dans l'export mais pas visible dans l'application)"),
                    ("PRIVATE", "Privé (pas dans l'export ni dans l'application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_audio_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer audio explanation (link)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_audio_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer audio explanation (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_book_recommendation",
            field=models.TextField(blank=True, verbose_name="Answer reading recommandation"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_choice_a",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer a"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_choice_b",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer b"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_choice_c",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer c"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_choice_d",
            field=models.CharField(blank=True, max_length=500, verbose_name="Answer d"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_correct",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "a"),
                    ("b", "b"),
                    ("c", "c"),
                    ("d", "d"),
                    ("ab", "ab"),
                    ("ac", "ac"),
                    ("ad", "ad"),
                    ("bc", "bc"),
                    ("bd", "bd"),
                    ("cd", "cd"),
                    ("abc", "abc"),
                    ("abd", "abd"),
                    ("acd", "acd"),
                    ("bcd", "bcd"),
                    ("abcd", "abcd"),
                ],
                help_text="a, b, c ou d (ab, acd, abcd… if multiple answers)",
                max_length=50,
                verbose_name="The correct answer",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_explanation",
            field=models.TextField(blank=True, verbose_name="Answer explanation"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_extra_info",
            field=models.TextField(
                blank=True, help_text="Won't be displayed in the application", verbose_name="Answer extra info"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_image_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer image (link)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_image_url_text",
            field=models.TextField(
                blank=True,
                help_text="Caption, translation, short explanation…",
                verbose_name="Answer image (text to display)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_source_accessible_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer accessible source (link)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_source_accessible_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer accessible source (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_source_scientific_url",
            field=models.URLField(
                blank=True,
                help_text="Report, scientific article…",
                max_length=500,
                verbose_name="Answer scientific source (link)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_source_scientific_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer scientific source (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_video_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Answer video explanation (link)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_video_url_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Answer video explanation (text to display)"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="author_string",
            field=models.CharField(blank=True, max_length=300, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="categories.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category_string",
            field=models.CharField(blank=True, max_length=50, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="question",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                choices=[(0, "Junior"), (1, "Facile"), (2, "Moyen"), (3, "Difficile"), (4, "Expert")],
                default=1,
                verbose_name="Difficulty level",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="has_ordered_answers",
            field=models.BooleanField(
                default=True,
                help_text="True if the answer choices should be displayed in this particular order (instead of being mixed up)",
                verbose_name="Ordered answers?",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="hint",
            field=models.TextField(
                blank=True, help_text="Text that the user can decide to display to help him", verbose_name="Hint"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="language",
            field=models.CharField(
                choices=[("Français", "Français"), ("English", "English"), ("Deutsch", "Deutsch")],
                default="Français",
                max_length=50,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(help_text="Keep it simple", verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="question",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
        migrations.AlterField(
            model_name="question",
            name="validation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Validation date"),
        ),
        migrations.AlterField(
            model_name="question",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("A valider", "A valider"),
                    ("Validée", "Validée"),
                    ("Écartée temporairement", "Écartée temporairement"),
                    ("Écartée", "Écartée"),
                ],
                default="Brouillon",
                max_length=150,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions_validated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validator",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="validator_string",
            field=models.CharField(blank=True, max_length=300, verbose_name="Validator"),
        ),
        migrations.AlterField(
            model_name="question",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Publique (dans l'export et dans l'application)"),
                    ("HIDDEN", "Caché (dans l'export mais pas visible dans l'application)"),
                    ("PRIVATE", "Privé (pas dans l'export ni dans l'application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibility",
            ),
        ),
    ]
