# Generated by Django 4.1.5 on 2023-02-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0022_question_language_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="difficulty",
            field=models.IntegerField(
                choices=[(0, "Junior"), (1, "Easy"), (2, "Medium"), (3, "Hard"), (4, "Expert")],
                default=1,
                verbose_name="Difficulty level",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="language",
            field=models.CharField(
                choices=[("FRENCH", "French"), ("ENGLISH", "English"), ("GERMAN", "German")],
                default="FRENCH",
                max_length=50,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="type",
            field=models.CharField(
                choices=[
                    ("QCM", "Multiple choice questionnaire"),
                    ("QCM-RM", "Multiple choice questionnaire with multiple answers"),
                    ("VF", "True or False"),
                ],
                default="QCM",
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (exported and the application)"),
                    ("HIDDEN", "Hidden (exported but not visible in the application)"),
                    ("PRIVATE", "Private (not exported and not in the application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.IntegerField(
                choices=[(0, "Junior"), (1, "Easy"), (2, "Medium"), (3, "Hard"), (4, "Expert")],
                default=1,
                verbose_name="Difficulty level",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="language",
            field=models.CharField(
                choices=[("FRENCH", "French"), ("ENGLISH", "English"), ("GERMAN", "German")],
                default="FRENCH",
                max_length=50,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("QCM", "Multiple choice questionnaire"),
                    ("QCM-RM", "Multiple choice questionnaire with multiple answers"),
                    ("VF", "True or False"),
                ],
                default="QCM",
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (exported and the application)"),
                    ("HIDDEN", "Hidden (exported but not visible in the application)"),
                    ("PRIVATE", "Private (not exported and not in the application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibility",
            ),
        ),
    ]
