# Generated by Django 4.1.5 on 2023-02-19 10:30

from django.db import migrations


def migrate_question_validation_status(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(validation_status="Brouillon").update(validation_status="DRAFT")
    Question.objects.filter(validation_status="A valider").update(validation_status="TO_VALIDATE")
    Question.objects.filter(validation_status="Validée").update(validation_status="VALIDATED")
    Question.objects.filter(validation_status="Écartée temporairement").update(validation_status="ASIDE")
    Question.objects.filter(validation_status="Écartée").update(validation_status="REMOVED")


def migrate_historical_question_validation_status(apps, schema_editor):
    HistoricalQuestion = apps.get_model("questions", "HistoricalQuestion")
    HistoricalQuestion.objects.filter(validation_status="Brouillon").update(validation_status="DRAFT")
    HistoricalQuestion.objects.filter(validation_status="A valider").update(validation_status="TO_VALIDATE")
    HistoricalQuestion.objects.filter(validation_status="Validée").update(validation_status="VALIDATED")
    HistoricalQuestion.objects.filter(validation_status="Écartée temporairement").update(validation_status="ASIDE")
    HistoricalQuestion.objects.filter(validation_status="Écartée").update(validation_status="REMOVED")


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0023_alter_historicalquestion_difficulty_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_question_validation_status),
        migrations.RunPython(migrate_historical_question_validation_status),
    ]
