# Generated by Django 4.1.5 on 2023-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0024_question_validation_status_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("TO_VALIDATE", "To validate"),
                    ("VALIDATED", "Validated"),
                    ("ASIDE", "Set aside"),
                    ("REMOVED", "Removed"),
                ],
                default="DRAFT",
                max_length=150,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("TO_VALIDATE", "To validate"),
                    ("VALIDATED", "Validated"),
                    ("ASIDE", "Set aside"),
                    ("REMOVED", "Removed"),
                ],
                default="DRAFT",
                max_length=150,
                verbose_name="Status",
            ),
        ),
    ]
