# Generated by Django 4.1.5 on 2023-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0025_alter_historicalquestion_validation_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="language",
            field=models.CharField(
                choices=[
                    ("FRENCH", "French"),
                    ("ENGLISH", "English"),
                    ("SPANISH", "Spanish"),
                    ("ITALIAN", "Italian"),
                    ("GERMAN", "German"),
                ],
                default="FRENCH",
                max_length=50,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="language",
            field=models.CharField(
                choices=[
                    ("FRENCH", "French"),
                    ("ENGLISH", "English"),
                    ("SPANISH", "Spanish"),
                    ("ITALIAN", "Italian"),
                    ("GERMAN", "German"),
                ],
                default="FRENCH",
                max_length=50,
                verbose_name="Language",
            ),
        ),
    ]
