# Generated by Django 4.2.9 on 2024-05-28 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0029_question_author_certify_and_author_agree"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionRelationship",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("remplacement", "remplacement"), ("traduction", "traduction")],
                        max_length=50,
                        verbose_name="Relationship type",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Creation date")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Last update date")),
                (
                    "from_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_questions",
                        to="questions.question",
                    ),
                ),
                (
                    "to_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_questions",
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
