[tool.black]
line-length = 119

[tool.flake8]
# exclude = .git, *migrations*, venv, app/settings.py
max-line-length = 119
ignore = "E203, W503"

[tool.isort]
combine_as_imports = true
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = "lemarche"
lines_after_imports = 2
line_length = 119
multi_line_output = 3
use_parentheses = true
