# Generated by Django 4.0.4 on 2022-05-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="application_open_source_code_url",
            field=models.URLField(
                default="https://github.com/quiz-anthropocene",
                editable=False,
                help_text="Le lien vers le code de l'application",
                max_length=500,
            ),
        ),
    ]
