# Generated by Django 4.2.9 on 2025-03-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_configuration_application_open_source_code_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="helloasso_url",
            field=models.URLField(
                blank=True, help_text="Le lien vers la page HelloAsso de l'association", max_length=500
            ),
        ),
    ]
