# Generated by Django 4.2.9 on 2025-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_configuration_helloasso_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="office_address",
            field=models.CharField(blank=True, help_text="L'adresse du bureau de l'association", max_length=255),
        ),
        migrations.AddField(
            model_name="configuration",
            name="office_url",
            field=models.URLField(
                blank=True, help_text="Le lien vers la page du bureau de l'association", max_length=500
            ),
        ),
    ]
