# Generated by Django 4.0.4 on 2022-05-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0004_add_verbose_names"),
        ("questions", "0004_add_verbose_names"),
        ("contributions", "0002_contribution_question_contribution_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="description",
            field=models.TextField(blank=True, verbose_name="Information supplémentaire"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="questions.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="quizs.quiz",
                verbose_name="Quiz",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="text",
            field=models.TextField(help_text="Une question, un commentaire…", verbose_name="Texte"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nouvelle question", "nouvelle question"),
                    ("nouveau quiz", "nouveau quiz"),
                    ("commentaire application", "commentaire application"),
                    ("commentaire question", "commentaire question"),
                    ("commentaire quiz", "commentaire quiz"),
                    ("nom application", "nom application"),
                    ("erreur application", "erreur application"),
                ],
                max_length=150,
                verbose_name="Type",
            ),
        ),
    ]
