# Generated by Django 4.1a1 on 2022-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0004_contribution_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Date de dernière modification"),
        ),
    ]
