# Generated by Django 4.1a1 on 2022-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0005_contribution_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "À traiter"),
                    ("PROCESSED", "Traité"),
                    ("REPLIED", "Répondu"),
                    ("IGNORED", "Ignoré"),
                ],
                max_length=150,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW_QUESTION", "Nouvelle question"),
                    ("NEW_QUIZ", "Nouveau quiz"),
                    ("COMMENT_APP", "Commentaire application"),
                    ("COMMENT_QUESTION", "Commentaire question"),
                    ("COMMENT_QUIZ", "Commentaire quiz"),
                    ("REPLY", "Réponse"),
                    ("ERROR_APP", "Erreur application"),
                ],
                max_length=150,
                verbose_name="Type",
            ),
        ),
    ]
