# Generated by Django 4.1a1 on 2022-05-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0006_contribution_status_and_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="contributions.contribution",
                verbose_name="En réponse à",
            ),
        ),
    ]
