# Generated by Django 4.1a1 on 2022-05-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0007_contribution_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "À traiter"),
                    ("PENDING", "En cours"),
                    ("PROCESSED", "Traité"),
                    ("REPLIED", "Répondu"),
                    ("IGNORED", "Ignoré"),
                ],
                max_length=150,
                verbose_name="Statut",
            ),
        ),
    ]
