# Generated by Django 4.1a1 on 2022-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0008_alter_contribution_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW_QUESTION", "Nouvelle question"),
                    ("NEW_QUIZ", "Nouveau quiz"),
                    ("COMMENT_APP", "Commentaire application"),
                    ("COMMENT_QUESTION", "Commentaire question"),
                    ("COMMENT_QUIZ", "Commentaire quiz"),
                    ("COMMENT_CONTRIBUTOR", "Commentaire contributeur"),
                    ("REPLY", "Réponse contributeur"),
                    ("ERROR_APP", "Erreur application"),
                ],
                max_length=150,
                verbose_name="Type",
            ),
        ),
    ]
