# Generated by Django 4.2a1 on 2023-03-10 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contributions", "0010_alter_contribution_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="description",
            field=models.TextField(blank=True, verbose_name="Addtional nformation"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="contributions.contribution",
                verbose_name="In answer to",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "À traiter"),
                    ("PENDING", "En cours"),
                    ("PROCESSED", "Traité"),
                    ("REPLIED", "Répondu"),
                    ("IGNORED", "Ignoré"),
                ],
                max_length=150,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="text",
            field=models.TextField(help_text="A question, a comment…", verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
    ]
