# Generated by Django 4.2a1 on 2023-03-10 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contributions", "0010_alter_contribution_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="description",
            field=models.TextField(blank=True, verbose_name="Additional information"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="contributions.contribution",
                verbose_name="In reply to",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "To process"),
                    ("PENDING", "In progress"),
                    ("PROCESSED", "Processed"),
                    ("REPLIED", "Replied"),
                    ("IGNORED", "Ignored"),
                ],
                max_length=150,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="text",
            field=models.TextField(help_text="A question, a comment…", verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW_QUESTION", "New question"),
                    ("NEW_QUIZ", "New quiz"),
                    ("COMMENT_APP", "Comment about the app"),
                    ("COMMENT_QUESTION", "Comment about a question"),
                    ("COMMENT_QUIZ", "Comment about a quiz"),
                    ("COMMENT_CONTRIBUTOR", "Contributor comment"),
                    ("REPLY", "Reply"),
                    ("ERROR_APP", "Application error"),
                ],
                max_length=150,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update date"),
        ),
    ]
