# Generated by Django 4.1.5 on 2023-03-20 15:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0028_alter_historicalquestion_history_changed_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizs", "0028_alter_historicalquiz_history_changed_fields"),
        ("contributions", "0011_contribution_model_translation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contribution",
            new_name="Comment",
        ),
    ]
