# Generated by Django 4.1.5 on 2023-03-20 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0028_alter_historicalquestion_history_changed_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizs", "0028_alter_historicalquiz_history_changed_fields"),
        ("contributions", "0012_rename_contribution_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created"], "verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="questions.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="quizs.quiz",
                verbose_name="Quiz",
            ),
        ),
    ]
