# Generated by Django 4.1.5 on 2023-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0013_comment_meta_and_rename_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "To process"),
                    ("PENDING", "In progress"),
                    ("PROCESSED", "Processed"),
                    ("IGNORED", "Ignored"),
                ],
                max_length=150,
                verbose_name="Status",
            ),
        ),
    ]
