# Generated by Django 4.1.5 on 2023-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0015_historicalcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="publish",
            field=models.BooleanField(
                default=False,
                help_text="Display the comment publicly (and its reply if it exists)",
                verbose_name="Published?",
            ),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="publish",
            field=models.BooleanField(
                default=False,
                help_text="Display the comment publicly (and its reply if it exists)",
                verbose_name="Published?",
            ),
        ),
    ]
