# Generated by Django 3.0.4 on 2020-03-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_model_questionstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_image_link',
            field=models.TextField(blank=True, help_text="Un lien vers une image pour illustrer la réponse (idéalement avec la source indiquée en bas de l'image)"),
        ),
    ]
