# Generated by Django 3.0.4 on 2020-03-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_question_answer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True, help_text='La date & heure de la contribution')),
            ],
        ),
    ]
