# Generated by Django 3.0.4 on 2020-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_create_model_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_image_link',
            field=models.URLField(blank=True, help_text="Un lien vers une image pour illustrer la réponse (idéalement avec la source indiquée quelque part sur l'image)", max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_additional_links',
            field=models.URLField(blank=True, help_text='Un lien pour aller plus loin', max_length=500),
        ),
        migrations.RenameField(
            model_name='question',
            old_name="answer_additional_links",
            new_name="answer_additional_link",
        ),
    ]
