# Generated by Django 3.0.4 on 2020-04-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200402_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Le nom du tag', max_length=50)),
                ('description', models.TextField(help_text='Une description du tag')),
                ('created', models.DateField(auto_now=True, help_text='La date & heure de la création du tag')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answer_extra_info',
            field=models.TextField(blank=True, help_text="Texte et liens explicatifs additionels, qui n'apparaissent pas dans l'interface"),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('biodiversité', 'Biodiversité'), ('climat', 'Climat'), ('consommation', "Consommation, Leviers d'action"), ('énergie', 'Energie'), ('histoire', 'Histoire, Anthropologie, Politique, Démographie'), ('pollution', 'Pollution'), ('ressources', 'Ressources (hors énergie)'), ('autre', 'Autre')], help_text='Une seule catégorie possible parmi la liste', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('QCM', 'Questionnaire à choix multiples (QCM)'), ('VF', 'Vrai ou Faux')], help_text='Le type de question (QCM, V/F, ...)', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(help_text='Un ou plusieurs tags rattaché à la question', related_name='questions', to='api.QuestionTag'),
        ),
    ]
