# Generated by Django 3.0.4 on 2020-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_auto_20200417_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="publish",
            field=models.BooleanField(
                default=False, help_text="Le quiz est prêt à être publié"
            ),
        ),
    ]
