# Generated by Django 3.0.4 on 2020-04-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_auto_20200425_0008"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="answer_additional_link",
            new_name="answer_accessible_url",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer_image_link",
            new_name="answer_image_url",
        ),
        migrations.AddField(
            model_name="question",
            name="answer_scientific_url",
            field=models.URLField(
                blank=True,
                help_text="La source scientifique du chiffre (rapport)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                help_text="La date & heure de la création de la catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="La date & heure de la contribution"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="questionstat",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="La date & heure de la réponse"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created",
            field=models.DateField(
                auto_now_add=True, help_text="La date & heure de la création du quiz"
            ),
        ),
        migrations.AlterField(
            model_name="quizstat",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="La date & heure de la réponse"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created",
            field=models.DateField(
                auto_now_add=True, help_text="La date & heure de la création du tag"
            ),
        ),
    ]
