# Generated by Django 3.0.4 on 2020-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20200425_2030"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="is_question",
        ),
        migrations.AddField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nouvelle question", "nouvelle question"),
                    ("commentaire application", "commentaire application"),
                    ("commentaire question", "commentaire question"),
                ],
                help_text="Le type de contribution",
                max_length=150,
            ),
        ),
    ]
