# Generated by Django 3.0.4 on 2020-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_auto_20200523_1916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nouvelle question", "nouvelle question"),
                    ("commentaire application", "commentaire application"),
                    ("commentaire question", "commentaire question"),
                    ("commentaire quiz", "commentaire quiz"),
                ],
                help_text="Le type de contribution",
                max_length=150,
            ),
        ),
    ]
