# Generated by Django 3.0.4 on 2020-05-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_auto_20200523_2335"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuestionStat", new_name="QuestionAnswerEvent",
        ),
        migrations.RenameModel(
            old_name="QuestionFeedback", new_name="QuestionFeedbackEvent",
        ),
        migrations.RenameModel(old_name="QuizStat", new_name="QuizAnswerEvent",),
    ]
