# Generated by Django 3.0.4 on 2020-06-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_improve_model_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.TextField(blank=True, help_text="Un indice (optionnel)"),
        ),
    ]
