# Generated by Django 3.0.4 on 2020-09-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_quiz_introduction_conclusion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_option_a",
            field=models.CharField(help_text="La réponse a", max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_option_b",
            field=models.CharField(help_text="La réponse b", max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_option_c",
            field=models.CharField(
                blank=True, help_text="La réponse c", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_option_d",
            field=models.CharField(
                blank=True, help_text="La réponse d", max_length=500
            ),
        ),
    ]
