# Generated by Django 3.1.1 on 2020-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_quiz_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizanswerevent",
            name="question_count",
            field=models.IntegerField(default=0, editable=False, help_text="La nombre de questions du quiz"),
        ),
        migrations.AlterField(
            model_name="quizanswerevent",
            name="answer_success_count",
            field=models.IntegerField(
                default=0,
                editable=False,
                help_text="La nombre de réponses correctes trouvées par l'internaute",
            ),
        ),
    ]
