# Generated by Django 3.1.1 on 2020-11-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_quizanswerevent_question_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_name",
                    models.CharField(
                        default="Quiz de l'Anthropocène",
                        help_text="Le nom de l'application",
                        max_length=255,
                    ),
                ),
                (
                    "application_backend_url",
                    models.URLField(
                        blank=True,
                        help_text="Le lien vers le backend de l'application",
                        max_length=500,
                    ),
                ),
                (
                    "application_frontend_url",
                    models.URLField(
                        blank=True,
                        help_text="Le lien vers le frontend de l'application",
                        max_length=500,
                    ),
                ),
                (
                    "daily_stat_last_aggregated",
                    models.DateTimeField(
                        blank=True,
                        help_text="La dernière fois qu'a été lancé le script de mise à jour des Daily Stats",
                        null=True,
                    ),
                ),
                (
                    "notion_questions_scope_1_last_imported",
                    models.DateTimeField(
                        blank=True,
                        help_text="La dernière fois que les questions (lot 1) ont été importées depuis Notion",
                        null=True,
                    ),
                ),
                (
                    "notion_questions_scope_2_last_imported",
                    models.DateTimeField(
                        blank=True,
                        help_text="La dernière fois que les questions (lot 2) ont été importées depuis Notion",
                        null=True,
                    ),
                ),
                (
                    "notion_questions_scope_3_last_imported",
                    models.DateTimeField(
                        blank=True,
                        help_text="La dernière fois que les questions (lot 3) ont été importées depuis Notion",
                        null=True,
                    ),
                ),
                (
                    "notion_questions_scope_4_last_imported",
                    models.DateTimeField(
                        blank=True,
                        help_text="La dernière fois que les questions (lot 4) ont été importées depuis Notion",
                        null=True,
                    ),
                ),
                (
                    "github_last_exported",
                    models.DateTimeField(
                        blank=True,
                        help_text="La dernière fois que la donnée a été exportée vers Github",
                        null=True,
                    ),
                ),
            ],
            options={"verbose_name": "Configuration de l'application",},
        ),
    ]
