# Generated by Django 3.1.1 on 2020-12-01 12:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_create_model_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Une description de la catégorie"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="conclusion",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Une conclusion du quiz et des pistes pour aller plus loin",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="introduction",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Une description du quiz"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Une description du tag"
            ),
        ),
    ]
