# Generated by Django 3.1.1 on 2020-12-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_auto_20201207_1832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nouvelle question", "nouvelle question"),
                    ("nouveau quiz", "nouveau quiz"),
                    ("commentaire application", "commentaire application"),
                    ("commentaire question", "commentaire question"),
                    ("commentaire quiz", "commentaire quiz"),
                    ("nom application", "nom application"),
                    ("erreur application", "erreur application"),
                ],
                help_text="Le type de contribution",
                max_length=150,
            ),
        ),
    ]
