# Generated by Django 3.1.4 on 2020-12-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_auto_20201207_2349"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suivant", "suivant"),
                            ("jumeau", "jumeau"),
                            ("similaire", "similaire"),
                        ],
                        help_text="Le type de relation entre les deux quizs",
                        max_length=50,
                    ),
                ),
                (
                    "from_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_quizs",
                        to="api.quiz",
                    ),
                ),
                (
                    "to_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_quizs",
                        to="api.quiz",
                    ),
                ),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True,
                        help_text="La date & heure de la création de la relation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="relationships",
            field=models.ManyToManyField(
                help_text="Les quizs similaires ou liés",
                related_name="related_to",
                through="api.QuizRelationship",
                to="api.Quiz",
            ),
        ),
    ]
