# Generated by Django 3.1.4 on 2020-12-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_create_model_quiz_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="application_facebook_url",
            field=models.URLField(
                blank=True,
                help_text="Le lien vers la page Facebook de l'application",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="application_linkedin_url",
            field=models.URLField(
                blank=True,
                help_text="Le lien vers la page Linkedin de l'application",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="application_twitter_url",
            field=models.URLField(
                blank=True,
                help_text="Le lien vers la page Twitter de l'application",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="application_name",
            field=models.CharField(
                default="Quiz de l'Anthropocène",
                editable=False,
                help_text="Le nom de l'application",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="daily_stat_last_aggregated",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois qu'a été lancé le script de mise à jour des Daily Stats",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="github_last_exported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que la donnée a été exportée vers Github",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="notion_contributions_last_exported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que les contributions exportées vers Notion",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="notion_questions_scope_1_last_imported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que les questions (lot 1) ont été importées depuis Notion",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="notion_questions_scope_2_last_imported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que les questions (lot 2) ont été importées depuis Notion",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="notion_questions_scope_3_last_imported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que les questions (lot 3) ont été importées depuis Notion",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="notion_questions_scope_4_last_imported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que les questions (lot 4) ont été importées depuis Notion",
                null=True,
            ),
        ),
    ]
