# Generated by Django 3.1.4 on 2020-12-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_configuration_add_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="application_open_source_code_url",
            field=models.URLField(
                default="https://github.com/raphodn/know-your-planet",
                editable=False,
                help_text="Le lien vers le code de l'application",
                max_length=500,
            ),
        ),
    ]
