# Generated by Django 3.1.4 on 2021-01-11 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_quiz_questions_m2m_add_through"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="La date de création du lien",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
