# Generated by Django 3.1.4 on 2021-01-11 22:27

from django.db import migrations


def update_quiz_question_order(apps, schema_editor):
    Quiz = apps.get_model("api", "Quiz")
    quizs = Quiz.objects.all()
    for quiz in quizs:
        for index, quizquestion in enumerate(quiz.quizquestion_set.all()):
            quizquestion.order = index + 1
            quizquestion.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_quiz_questions_through_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizquestion",
            options={"ordering": ["quiz_id", "order"]},
        ),
        migrations.RunPython(update_quiz_question_order),
    ]
