# Generated by Django 3.1.4 on 2021-03-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0079_question_and_quiz_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_audio",
            field=models.URLField(
                blank=True, help_text="Une explication audio", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_video",
            field=models.URLField(
                blank=True, help_text="Une explication vidéo", max_length=500
            ),
        ),
    ]
