# Generated by Django 3.1.4 on 2021-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_question_audio_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configuration",
            old_name="github_last_exported",
            new_name="github_data_last_exported",
        ),
        migrations.AddField(
            model_name="configuration",
            name="github_stats_last_exported",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="La dernière fois que les stats ont été exportées vers Github",
                null=True,
            ),
        ),
    ]
