# Generated by Django 4.0.3 on 2022-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("api", "0091_delete_tag_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Un ou plusieurs tags rattaché à la question",
                related_name="questions",
                to="tags.tag",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="Un ou plusieurs tags rattaché au quiz", related_name="quizs", to="tags.tag"
            ),
        ),
    ]
