# Generated by Django 4.1.5 on 2023-02-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_linkclickevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkclickevent",
            name="field_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Nom du champ"),
        ),
    ]
