# Generated by Django 4.2a1 on 2023-03-10 23:56

import django.utils.timezone
from django.db import migrations, models

import stats.constants


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_alter_linkclickevent_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystat",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date & time of daily statistics"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="date",
            field=models.DateField(help_text="Date of statistics"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="hour_split",
            field=models.JSONField(
                default=stats.constants.daily_stat_hour_split_jsonfield_default_value, help_text="Hourly statistics"
            ),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="question_answer_count",
            field=models.PositiveIntegerField(default=0, help_text="Answered questions count"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="question_answer_from_quiz_count",
            field=models.PositiveIntegerField(default=0, help_text="Answered questions within quiz count"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="question_feedback_count",
            field=models.PositiveIntegerField(default=0, help_text="Question feedbacks count"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="question_feedback_from_quiz_count",
            field=models.PositiveIntegerField(default=0, help_text="Question feedbacks within quizzes count"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="question_public_answer_count",
            field=models.PositiveIntegerField(default=0, help_text="Answered public questions count"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="quiz_answer_count",
            field=models.PositiveIntegerField(default=0, help_text="Answered quizzes count"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="quiz_feedback_count",
            field=models.PositiveIntegerField(default=0, help_text="Quiz feedbacks count"),
        ),
        migrations.AlterField(
            model_name="dailystat",
            name="quiz_public_answer_count",
            field=models.PositiveIntegerField(default=0, help_text="Answered public quizzes count"),
        ),
        migrations.AlterField(
            model_name="linkclickevent",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date & time of click"),
        ),
        migrations.AlterField(
            model_name="linkclickevent",
            name="field_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Field name"),
        ),
        migrations.AlterField(
            model_name="linkclickevent",
            name="link_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Clicked link"),
        ),
        migrations.AlterField(
            model_name="questionaggstat",
            name="answer_count",
            field=models.PositiveIntegerField(default=0, help_text="Answers count"),
        ),
        migrations.AlterField(
            model_name="questionaggstat",
            name="answer_success_count",
            field=models.PositiveIntegerField(default=0, help_text="Right answers count"),
        ),
        migrations.AlterField(
            model_name="questionaggstat",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0, help_text="Dislikes count"),
        ),
        migrations.AlterField(
            model_name="questionaggstat",
            name="like_count",
            field=models.PositiveIntegerField(default=0, help_text="Likes count"),
        ),
        migrations.AlterField(
            model_name="questionanswerevent",
            name="choice",
            field=models.CharField(
                choices=[
                    ("a", "a"),
                    ("b", "b"),
                    ("c", "c"),
                    ("d", "d"),
                    ("ab", "ab"),
                    ("ac", "ac"),
                    ("ad", "ad"),
                    ("bc", "bc"),
                    ("bd", "bd"),
                    ("cd", "cd"),
                    ("abc", "abc"),
                    ("abd", "abd"),
                    ("acd", "acd"),
                    ("bcd", "bcd"),
                    ("abcd", "abcd"),
                ],
                help_text="Answer chosen by the internet user",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="questionanswerevent",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date & time of answer"),
        ),
        migrations.AlterField(
            model_name="questionanswerevent",
            name="source",
            field=models.CharField(
                choices=[("question", "Question"), ("quiz", "Quiz")],
                default="question",
                help_text="Context in which the question was answered",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="questionfeedbackevent",
            name="choice",
            field=models.CharField(
                choices=[("like", "Positive"), ("dislike", "Negative")],
                default="like",
                help_text="Opinion on the question",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="questionfeedbackevent",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date & time of the opinion"),
        ),
        migrations.AlterField(
            model_name="questionfeedbackevent",
            name="source",
            field=models.CharField(
                choices=[("question", "Question"), ("quiz", "Quiz")],
                default="question",
                help_text="the context in which the opinion was sent",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quizaggstat",
            name="answer_count",
            field=models.PositiveIntegerField(default=0, help_text="Answers count"),
        ),
        migrations.AlterField(
            model_name="quizaggstat",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0, help_text="Dislikes count"),
        ),
        migrations.AlterField(
            model_name="quizaggstat",
            name="like_count",
            field=models.PositiveIntegerField(default=0, help_text="Likes count"),
        ),
        migrations.AlterField(
            model_name="quizanswerevent",
            name="answer_success_count",
            field=models.IntegerField(default=0, help_text="Right answers count"),
        ),
        migrations.AlterField(
            model_name="quizanswerevent",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date and time of answer"),
        ),
        migrations.AlterField(
            model_name="quizanswerevent",
            name="duration_seconds",
            field=models.IntegerField(default=0, help_text="Duration(in seconds) to complete the quiz"),
        ),
        migrations.AlterField(
            model_name="quizanswerevent",
            name="question_answer_split",
            field=models.JSONField(default=dict, help_text="Details per question"),
        ),
        migrations.AlterField(
            model_name="quizanswerevent",
            name="question_count",
            field=models.IntegerField(default=0, help_text="Quiz questions count"),
        ),
        migrations.AlterField(
            model_name="quizfeedbackevent",
            name="choice",
            field=models.CharField(
                choices=[("like", "Positive"), ("dislike", "Negative")],
                default="like",
                help_text="Opinion left on the quiz",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quizfeedbackevent",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date & time of opinion"),
        ),
    ]
