# Generated by Django 4.0.3 on 2022-03-24 22:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Category",
                    fields=[
                        (
                            "id",
                            models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        ("name", models.CharField(help_text="Le nom de la catégorie", max_length=50)),
                        ("name_long", models.CharField(help_text="Le nom allongé de la catégorie", max_length=150)),
                        (
                            "description",
                            ckeditor.fields.RichTextField(blank=True, help_text="Une description de la catégorie"),
                        ),
                        (
                            "created",
                            models.DateField(auto_now_add=True, help_text="La date de création de la catégorie"),
                        ),
                    ],
                    options={
                        "verbose_name": "Category",
                        "verbose_name_plural": "Categories",
                        "ordering": ["pk"],
                    },
                ),
            ],
            # Table already exist, see api/migrations/0089_migrate_category_model.py
            database_operations=[],
        )
    ]
