# Generated by Django 4.0.4 on 2022-04-30 16:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_long",
            field=models.CharField(max_length=150, verbose_name="Nom (version longue)"),
        ),
    ]
