# Generated by Django 4.1 on 2022-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_id", models.IntegerField(blank=True, verbose_name="ID de l'acteur")),
                ("actor_name", models.CharField(blank=True, max_length=150, verbose_name="Nom de l'acteur")),
                (
                    "event_verb",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATED", "Créé"),
                            ("UPDATED", "Mis à jour"),
                            ("VALIDATED", "Validé"),
                            ("PUBLISHED", "Publié"),
                            ("DELETED", "Supprimé"),
                            ("COMPUTED", "Calculé"),
                        ],
                        max_length=50,
                        verbose_name="Verbe",
                    ),
                ),
                ("event_object_id", models.IntegerField(blank=True, verbose_name="ID de l'objet")),
                (
                    "event_object_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QUESTION", "Question"),
                            ("QUIZ", "Quiz"),
                            ("WEEKLY_AGG_STAT", "Statistiques de la semaine"),
                        ],
                        max_length=50,
                        verbose_name="Type d'objet",
                    ),
                ),
                ("event_object_name", models.CharField(blank=True, max_length=150, verbose_name="Nom de l'objet")),
                ("extra_data", models.JSONField(default=dict, verbose_name="Données supplémentaires")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
            ],
            options={"verbose_name": "Événement", "verbose_name_plural": "Événements"},
        ),
    ]
