# Generated by Django 4.2 on 2023-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0004_alter_event_actor_id_object_id_allow_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_object_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QUESTION", "Question"),
                    ("QUIZ", "Quiz"),
                    ("USER", "Contributor"),
                    ("WEEKLY_AGG_STAT", "Weekly statistics"),
                    ("MONTHLY_AGG_STAT", "Monthly statistics"),
                ],
                max_length=50,
                verbose_name="Object type",
            ),
        ),
    ]
