# Generated by Django 4.0.4 on 2022-05-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glossaryitem",
            name="definition_short",
            field=models.CharField(max_length=150, verbose_name="Définition (succinte)"),
        ),
        migrations.AlterField(
            model_name="glossaryitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="glossaryitem",
            name="description_accessible_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Lien pour aller plus loin"),
        ),
        migrations.AlterField(
            model_name="glossaryitem",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Mot ou sigle"),
        ),
        migrations.AlterField(
            model_name="glossaryitem",
            name="name_alternatives",
            field=models.TextField(blank=True, verbose_name="Noms alternatifs"),
        ),
    ]
