# Generated by Django 4.0.3 on 2022-03-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Glossary",
            new_name="GlossaryItem",
        ),
    ]
