# Generated by Django 4.1a1 on 2022-05-21 12:00

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("glossary", "0004_remove_glossaryitem_added_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGlossaryItem",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Mot ou sigle")),
                ("name_alternatives", models.TextField(blank=True, verbose_name="Noms alternatifs")),
                ("definition_short", models.CharField(max_length=150, verbose_name="Définition (succinte)")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "description_accessible_url",
                    models.URLField(blank=True, max_length=500, verbose_name="Lien pour aller plus loin"),
                ),
                ("created", models.DateTimeField(blank=True, editable=False, verbose_name="Date de création")),
                (
                    "updated",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Date de dernière modification"),
                ),
                (
                    "history_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical glossary item",
                "verbose_name_plural": "historical glossary items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
