# Generated by Django 4.1a1 on 2022-05-26 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0005_historicalglossaryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalglossaryitem",
            name="history_changed_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
                verbose_name="Champs modifiés",
            ),
        ),
    ]
