# Generated by Django 4.1.5 on 2023-02-23 09:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0007_alter_glossaryitem_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalglossaryitem",
            name="history_changed_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
                verbose_name="Changed fields",
            ),
        ),
    ]
