# Generated by Django 4.1.5 on 2023-02-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0009_glossaryitem_model_translate"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossaryitem",
            name="language",
            field=models.CharField(
                choices=[
                    ("FRENCH", "French"),
                    ("ENGLISH", "English"),
                    ("SPANISH", "Spanish"),
                    ("ITALIAN", "Italian"),
                    ("GERMAN", "German"),
                ],
                default="FRENCH",
                max_length=50,
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="historicalglossaryitem",
            name="language",
            field=models.CharField(
                choices=[
                    ("FRENCH", "French"),
                    ("ENGLISH", "English"),
                    ("SPANISH", "Spanish"),
                    ("ITALIAN", "Italian"),
                    ("GERMAN", "German"),
                ],
                default="FRENCH",
                max_length=50,
                verbose_name="Language",
            ),
        ),
    ]
