# Generated by Django 4.0.3 on 2022-03-27 10:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Le nom du tag", max_length=50)),
                ("description", ckeditor.fields.RichTextField(blank=True, help_text="Une description du tag")),
                ("created", models.DateField(auto_now_add=True, help_text="La date de création du tag")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["pk"],
            },
        ),
    ]
