# Generated by Django 4.0.3 on 2022-04-16 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="author_link",
            field=models.ForeignKey(
                help_text="L'auteur de la question",
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="validator_link",
            field=models.ForeignKey(
                blank=True,
                help_text="La personne qui a validée la question",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions_validated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
