# Generated by Django 4.0.3 on 2022-04-16 10:17

from django.db import migrations


def link_authors(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    User = apps.get_model("users", "User")
    for question in Question.objects.all():
        author = None
        question_author_split = question.author.split(" ")
        try:
            author = User.objects.get(first_name=question_author_split[0], last_name=question_author_split[1])
        except:  # noqa
            try:
                author = User.objects.get(first_name=question.author)
            except:  # noqa
                pass
        if author:
            question.author_link = author
            question.save()


def link_validators(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    User = apps.get_model("users", "User")
    for question in Question.objects.all():
        validator = None
        question_validator_split = question.validator.split(" ")
        try:
            validator = User.objects.get(first_name=question_validator_split[0], last_name=question_validator_split[1])
        except:  # noqa
            try:
                validator = User.objects.get(first_name=question.validator)
            except:  # noqa
                pass
        if validator:
            question.validator_link = validator
            question.save()


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_author_link_question_validator_link"),
    ]

    operations = [
        migrations.RunPython(link_authors),
        migrations.RunPython(link_validators),
    ]
