# Generated by Django 4.0.4 on 2022-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_add_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("QCM", "Questionnaire à choix multiples"),
                    ("QCM-RM", "Questionnaire à choix multiples avec réponses multiples"),
                    ("VF", "Vrai ou Faux"),
                ],
                default="QCM",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
