# Generated by Django 4.0.4 on 2022-05-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_question_timestamps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="author",
            new_name="author_old",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="author_link",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="validator",
            new_name="validator_old",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="validator_link",
            new_name="validator",
        ),
    ]
