# Generated by Django 4.0.4 on 2022-05-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_remove_historicalquestion_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquestion",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Publique (dans l'export et dans l'application)"),
                    ("HIDDEN", "Caché (dans l'export mais pas visible dans l'application)"),
                    ("PRIVATE", "Privé (pas dans l'export ni dans l'application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibilité",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Publique (dans l'export et dans l'application)"),
                    ("HIDDEN", "Caché (dans l'export mais pas visible dans l'application)"),
                    ("PRIVATE", "Privé (pas dans l'export ni dans l'application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibilité",
            ),
        ),
    ]
