# Generated by Django 4.0.3 on 2022-03-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quizs", "0002_create_quiz_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizRelationship",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suivant", "suivant"),
                            ("jumeau", "jumeau"),
                            ("similaire", "similaire"),
                            ("traduction", "traduction"),
                        ],
                        help_text="Le type de relation entre les deux quizs",
                        max_length=50,
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, help_text="La date & heure de la création de la relation"),
                ),
                (
                    "from_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="from_quizs", to="quizs.quiz"
                    ),
                ),
                (
                    "to_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="to_quizs", to="quizs.quiz"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="relationships",
            field=models.ManyToManyField(
                help_text="Les quizs similaires ou liés",
                related_name="related_to",
                through="quizs.QuizRelationship",
                to="quizs.quiz",
            ),
        ),
    ]
