# Generated by Django 4.0.4 on 2022-04-30 16:12

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_add_verbose_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0002_add_verbose_names"),
        ("quizs", "0003_populate_quiz_author_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="author",
            field=models.CharField(blank=True, max_length=50, verbose_name="Auteur"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="author_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="conclusion",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="Inclure des pistes pour aller plus loin", verbose_name="Conclusion"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="difficulty_average",
            field=models.FloatField(default=0, verbose_name="Difficulté moyenne"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="has_audio",
            field=models.BooleanField(default=False, verbose_name="Contenu audio ?"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="image_background_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Lien vers une image pour illustrer le quiz"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="introduction",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Introduction"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="language",
            field=models.CharField(
                choices=[("Français", "Français"), ("English", "English")],
                default="Français",
                max_length=50,
                verbose_name="Langue",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="publish",
            field=models.BooleanField(default=False, verbose_name="Prêt à être publié ?"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                related_name="quizs",
                through="quizs.QuizQuestion",
                to="questions.question",
                verbose_name="Les questions",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="relationships",
            field=models.ManyToManyField(
                related_name="related_to",
                through="quizs.QuizRelationship",
                to="quizs.quiz",
                verbose_name="Les quizs similaires ou liés",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Fragment d'URL"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="spotlight",
            field=models.BooleanField(default=False, verbose_name="Mise en avant ?"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="quizs", to="tags.tag", verbose_name="Tag(s)"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="updated",
            field=models.DateField(auto_now=True, verbose_name="Date de dernière modification"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.question", verbose_name="Question"
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="quiz",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizs.quiz", verbose_name="Quiz"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="updated",
            field=models.DateField(auto_now=True, verbose_name="Date de dernière modification"),
        ),
        migrations.AlterField(
            model_name="quizrelationship",
            name="created",
            field=models.DateField(auto_now_add=True, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="quizrelationship",
            name="status",
            field=models.CharField(
                choices=[
                    ("suivant", "suivant"),
                    ("jumeau", "jumeau"),
                    ("similaire", "similaire"),
                    ("traduction", "traduction"),
                ],
                max_length=50,
                verbose_name="Type de relation",
            ),
        ),
    ]
