# Generated by Django 4.0.3 on 2022-03-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
        ("quizs", "0003_create_quiz_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                help_text="Les questions du quiz",
                related_name="quizs",
                through="quizs.QuizQuestion",
                to="questions.question",
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questions.question"),
        ),
    ]
