# Generated by Django 4.0.4 on 2022-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0010_quiz_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizrelationship",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Date de dernière modification"),
        ),
    ]
