# Generated by Django 4.1a1 on 2022-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0014_alter_historicalquiz_language_alter_quiz_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquiz",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de publication"),
        ),
    ]
