# Generated by Django 4.1a1 on 2022-07-21 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizs", "0015_historicalquiz_publish_date_quiz_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquiz",
            name="validation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
        ),
        migrations.AddField(
            model_name="historicalquiz",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("A valider", "A valider"),
                    ("Validée", "Validée"),
                    ("Écartée temporairement", "Écartée temporairement"),
                    ("Écartée", "Écartée"),
                ],
                default="Brouillon",
                max_length=150,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="historicalquiz",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validateur",
            ),
        ),
        migrations.AddField(
            model_name="historicalquiz",
            name="validator_string",
            field=models.CharField(blank=True, max_length=300, verbose_name="Validateur"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="validation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("Brouillon", "Brouillon"),
                    ("A valider", "A valider"),
                    ("Validée", "Validée"),
                    ("Écartée temporairement", "Écartée temporairement"),
                    ("Écartée", "Écartée"),
                ],
                default="Brouillon",
                max_length=150,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="validator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizs_validated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validateur",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="validator_string",
            field=models.CharField(blank=True, max_length=300, verbose_name="Validateur"),
        ),
    ]
