# Generated by Django 4.1 on 2022-08-17 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0016_quiz_validation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquiz",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
        migrations.AlterField(
            model_name="quizrelationship",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création"),
        ),
    ]
