# Generated by Django 4.1 on 2022-09-03 20:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_created"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizs", "0017_alter_historicalquiz_created_alter_quiz_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAuthors",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Createur", "Createur"),
                            ("Contributeur", "Contributeur"),
                            ("Rédacteur", "Rédacteur"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Type de role",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalquiz",
            name="authors_id_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Auteurs_ID",
            ),
        ),
        migrations.AddField(
            model_name="historicalquiz",
            name="authors_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name="Auteurs"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="quizs",
                through="quizs.QuizAuthors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteurs",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="authors_id_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Auteurs_ID",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="authors_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name="Auteurs"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="old_quizs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AddField(
            model_name="quizauthors",
            name="quiz",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizs.quiz", verbose_name="Quiz"),
        ),
    ]
