# Generated by Django 4.1 on 2022-08-26 10:48

from django.db import migrations, models
from django.db.models.functions import Concat


def forward(apps, schema_editor):
    Quizs = apps.get_model("quizs", "Quiz")
    for quiz in Quizs.objects.all():
        quiz.authors.add(quiz.author)
        quiz.authors_list = list(
            quiz.authors.annotate(fullname=Concat("first_name", models.Value(" "), "last_name")).values_list(
                "fullname", flat=True
            )
        )
        quiz.authors_id_list = list(quiz.authors.values_list("id", flat=True))
        quiz.save()


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0018_quizauthors_historicalquiz_authors_id_list_and_more"),
    ]

    operations = [migrations.RunPython(forward)]
