# Generated by Django 4.1 on 2022-08-26 10:48

from django.db import migrations, models


def forward(apps, schema_editor):
    Quizs = apps.get_model("quizs", "Quiz")
    for quiz in Quizs.objects.all():
        quiz.authors.add(quiz.author)


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0018_quizauthors_historicalquiz_authors_id_list_and_more"),
    ]

    operations = [migrations.RunPython(forward)]
