# Generated by Django 4.1 on 2022-08-26 10:48

from django.db import migrations, models
from django.db.models.functions import Concat


def forward(apps, schema_editor):
    Quiz = apps.get_model("quizs", "Quiz")
    for quiz in Quiz.objects.all():
        quiz.authors.set([quiz.author])
        quiz.author_list = list(
            quiz.authors.annotate(fullname=Concat("first_name", models.Value(" "), "last_name")).values_list(
                "fullname", flat=True
            )
        )
        quiz.save()


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0018_quizauthor_historicalquiz_author_list_and_more"),
    ]

    operations = [migrations.RunPython(forward)]
