# Generated by Django 4.1 on 2022-09-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0019_forward_data_author_to_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalquiz",
            name="author",
        ),
        migrations.RemoveField(
            model_name="historicalquiz",
            name="author_string",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="author",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="author_string",
        ),
    ]
