# Generated by Django 4.1 on 2022-09-14 22:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizs", "0019_forward_data_author_to_authors"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="quizauthor",
            unique_together={("quiz", "author")},
        ),
    ]
