# Generated by Django 4.1.5 on 2023-02-18 19:54

from django.db import migrations


def migrate_quiz_language(apps, schema_editor):
    Quiz = apps.get_model("quizs", "Quiz")
    Quiz.objects.filter(language="Français").update(language="FRENCH")
    Quiz.objects.filter(language="English").update(language="ENGLISH")
    Quiz.objects.filter(language="Deutsch").update(language="GERMAN")


def migrate_historical_quiz_language(apps, schema_editor):
    HistoricalQuiz = apps.get_model("quizs", "HistoricalQuiz")
    HistoricalQuiz.objects.filter(language="Français").update(language="FRENCH")
    HistoricalQuiz.objects.filter(language="English").update(language="ENGLISH")
    HistoricalQuiz.objects.filter(language="Deutsch").update(language="GERMAN")


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0020_remove_historicalquiz_author_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_quiz_language),
        migrations.RunPython(migrate_historical_quiz_language),
    ]
