# Generated by Django 4.1.5 on 2023-02-19 10:30

from django.db import migrations


def migrate_quiz_validation_status(apps, schema_editor):
    Quiz = apps.get_model("quizs", "Quiz")
    Quiz.objects.filter(validation_status="Brouillon").update(validation_status="DRAFT")
    Quiz.objects.filter(validation_status="A valider").update(validation_status="TO_VALIDATE")
    Quiz.objects.filter(validation_status="Validée").update(validation_status="VALIDATED")
    Quiz.objects.filter(validation_status="Écartée temporairement").update(validation_status="ASIDE")
    Quiz.objects.filter(validation_status="Écartée").update(validation_status="REMOVED")


def migrate_historical_quiz_validation_status(apps, schema_editor):
    HistoricalQuiz = apps.get_model("quizs", "HistoricalQuiz")
    HistoricalQuiz.objects.filter(validation_status="Brouillon").update(validation_status="DRAFT")
    HistoricalQuiz.objects.filter(validation_status="A valider").update(validation_status="TO_VALIDATE")
    HistoricalQuiz.objects.filter(validation_status="Validée").update(validation_status="VALIDATED")
    HistoricalQuiz.objects.filter(validation_status="Écartée temporairement").update(validation_status="ASIDE")
    HistoricalQuiz.objects.filter(validation_status="Écartée").update(validation_status="REMOVED")


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0022_alter_historicalquiz_language_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_quiz_validation_status),
        migrations.RunPython(migrate_historical_quiz_validation_status),
    ]
