# Generated by Django 4.1.5 on 2023-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0023_quiz_validation_status_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquiz",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("TO_VALIDATE", "To validate"),
                    ("VALIDATED", "Validated"),
                    ("ASIDE", "Set aside"),
                    ("REMOVED", "Removed"),
                ],
                default="DRAFT",
                max_length=150,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("TO_VALIDATE", "To validate"),
                    ("VALIDATED", "Validated"),
                    ("ASIDE", "Set aside"),
                    ("REMOVED", "Removed"),
                ],
                default="DRAFT",
                max_length=150,
                verbose_name="Statut",
            ),
        ),
    ]
