# Generated by Django 4.1.5 on 2023-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0026_quiz_language_spanish_italian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquiz",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (exported and in the application)"),
                    ("HIDDEN", "Hidden (exported but not visible in the application)"),
                    ("PRIVATE", "Private (not exported and not in the application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public (exported and in the application)"),
                    ("HIDDEN", "Hidden (exported but not visible in the application)"),
                    ("PRIVATE", "Private (not exported and not in the application)"),
                ],
                default="PUBLIC",
                max_length=50,
                verbose_name="Visibility",
            ),
        ),
    ]
