# Generated by Django 3.2.4 on 2021-06-05 21:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Configuration",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "application_name",
                            models.CharField(
                                default="Quiz de l'Anthropocène",
                                editable=False,
                                help_text="Le nom de l'application",
                                max_length=255,
                            ),
                        ),
                        (
                            "application_tagline",
                            models.CharField(
                                help_text="La tagline de l'application", max_length=255
                            ),
                        ),
                        (
                            "application_about",
                            ckeditor.fields.RichTextField(
                                blank=True, help_text="A propos de l'application"
                            ),
                        ),
                        (
                            "application_open_source_code_url",
                            models.URLField(
                                default="https://github.com/raphodn/know-your-planet",
                                editable=False,
                                help_text="Le lien vers le code de l'application",
                                max_length=500,
                            ),
                        ),
                        (
                            "application_backend_url",
                            models.URLField(
                                blank=True,
                                help_text="Le lien vers le backend de l'application",
                                max_length=500,
                            ),
                        ),
                        (
                            "application_frontend_url",
                            models.URLField(
                                blank=True,
                                help_text="Le lien vers le frontend de l'application",
                                max_length=500,
                            ),
                        ),
                        (
                            "application_frontend_ecoindex_url",
                            models.URLField(
                                blank=True,
                                help_text="Le lien vers le test EcoIndex.fr du frontend",
                                max_length=500,
                            ),
                        ),
                        (
                            "application_facebook_url",
                            models.URLField(
                                blank=True,
                                help_text="Le lien vers la page Facebook de l'application",
                                max_length=500,
                            ),
                        ),
                        (
                            "application_twitter_url",
                            models.URLField(
                                blank=True,
                                help_text="Le lien vers la page Twitter de l'application",
                                max_length=500,
                            ),
                        ),
                        (
                            "application_linkedin_url",
                            models.URLField(
                                blank=True,
                                help_text="Le lien vers la page Linkedin de l'application",
                                max_length=500,
                            ),
                        ),
                        (
                            "daily_stat_last_aggregated",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois qu'a été lancé le script de mise à jour des Daily Stats",
                                null=True,
                            ),
                        ),
                        (
                            "notion_questions_scope_1_last_imported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que les questions (lot 1) ont été importées depuis Notion",
                                null=True,
                            ),
                        ),
                        (
                            "notion_questions_scope_2_last_imported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que les questions (lot 2) ont été importées depuis Notion",
                                null=True,
                            ),
                        ),
                        (
                            "notion_questions_scope_3_last_imported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que les questions (lot 3) ont été importées depuis Notion",
                                null=True,
                            ),
                        ),
                        (
                            "notion_questions_scope_4_last_imported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que les questions (lot 4) ont été importées depuis Notion",
                                null=True,
                            ),
                        ),
                        (
                            "notion_questions_scope_5_last_imported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que les questions (lot 5) ont été importées depuis Notion",
                                null=True,
                            ),
                        ),
                        (
                            "github_data_last_exported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que la donnée a été exportée vers Github",
                                null=True,
                            ),
                        ),
                        (
                            "github_stats_last_exported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que les stats ont été exportées vers Github",
                                null=True,
                            ),
                        ),
                        (
                            "notion_contributions_last_exported",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                help_text="La dernière fois que les contributions exportées vers Notion",
                                null=True,
                            ),
                        ),
                    ],
                    options={"verbose_name": "Configuration de l'application",},
                ),
            ],
            # Table already exists. See api/migrations/0082_delete_configuration.py
            database_operations=[],
        )
    ]
