# Generated by Django 4.0.3 on 2022-04-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0003_populate_quiz_author_link"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswerevent",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_stats",
                to="quizs.quiz",
            ),
        ),
        migrations.AddField(
            model_name="questionfeedbackevent",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_feedbacks",
                to="quizs.quiz",
            ),
        ),
    ]
