# Generated by Django 3.1.4 on 2021-02-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_migrate_stats_models"),
    ]

    operations = [
        # api_questionaggstat, api_questionanswerevent, api_quizanswerevent
        migrations.RunSQL(
            "alter sequence api_dailystat_id_seq rename to stats_dailystat_id_seq;"
        ),
        migrations.RunSQL(
            "alter sequence api_questionstat_id_seq rename to stats_questionanswerevent_id_seq;"
        ),
        migrations.RunSQL(
            "alter sequence api_questionfeedback_id_seq rename to stats_questionfeedbackevent_id_seq;"
        ),
        migrations.RunSQL(
            "alter sequence api_quizstat_id_seq rename to stats_quizanswerevent_id_seq;"
        ),
        migrations.RunSQL(
            "alter sequence api_quizfeedbackevent_id_seq rename to stats_quizfeedbackevent_id_seq;"
        ),
    ]
