# Generated by Django 4.0.3 on 2022-03-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0001_create_quiz"),
        ("stats", "0005_remove_editable_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizanswerevent",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="quizs.quiz"
            ),
        ),
        migrations.AlterField(
            model_name="quizfeedbackevent",
            name="quiz",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="quizs.quiz"
            ),
        ),
    ]
