# Generated by Django 4.0.3 on 2022-03-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0004_alter_quiz_questions_alter_quizquestion_question"),
        ("stats", "0007_alter_questionaggstat_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAggStat",
            fields=[
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="agg_stats",
                        serialize=False,
                        to="quizs.quiz",
                    ),
                ),
                ("answer_count", models.PositiveIntegerField(default=0, help_text="Le nombre de réponses")),
                ("like_count", models.PositiveIntegerField(default=0, help_text="Le nombre de likes")),
                ("dislike_count", models.PositiveIntegerField(default=0, help_text="Le nombre de dislikes")),
            ],
        ),
    ]
