# Generated by Django 4.0.3 on 2022-03-27 17:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0093_remove_quiz_questions_remove_quiz_relationships_and_more"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Le nom du quiz", max_length=50)),
                ("slug", models.SlugField(help_text="Le bout d'url du quiz", unique=True)),
                ("introduction", ckeditor.fields.RichTextField(blank=True, help_text="Une description du quiz")),
                (
                    "conclusion",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Une conclusion du quiz et des pistes pour aller plus loin"
                    ),
                ),
                ("difficulty_average", models.FloatField(default=0, help_text="La difficulté moyenne des questions")),
                (
                    "language",
                    models.CharField(
                        choices=[("Français", "Français"), ("English", "English")],
                        default="Français",
                        help_text="La langue du quiz",
                        max_length=50,
                    ),
                ),
                ("author", models.CharField(blank=True, help_text="L'auteur du quiz", max_length=50)),
                (
                    "image_background_url",
                    models.URLField(
                        blank=True, help_text="Un lien vers une image pour illustrer le quiz", max_length=500
                    ),
                ),
                ("has_audio", models.BooleanField(default=False, help_text="Le quiz a du contenu audio")),
                ("publish", models.BooleanField(default=False, help_text="Le quiz est prêt à être publié")),
                ("spotlight", models.BooleanField(default=False, help_text="Le quiz est mis en avant")),
                ("created", models.DateField(auto_now_add=True, help_text="La date de création du quiz")),
                ("updated", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizs",
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="Un ou plusieurs tags rattaché au quiz", related_name="quizs", to="tags.tag"
            ),
        ),
    ]
