# Generated by Django 4.0.3 on 2022-03-30 22:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Le nom du quiz", max_length=50)),
                ("slug", models.SlugField(help_text="Le bout d'url du quiz", unique=True)),
                ("introduction", ckeditor.fields.RichTextField(blank=True, help_text="Une description du quiz")),
                (
                    "conclusion",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Une conclusion du quiz et des pistes pour aller plus loin"
                    ),
                ),
                ("difficulty_average", models.FloatField(default=0, help_text="La difficulté moyenne des questions")),
                (
                    "language",
                    models.CharField(
                        choices=[("Français", "Français"), ("English", "English")],
                        default="Français",
                        help_text="La langue du quiz",
                        max_length=50,
                    ),
                ),
                ("author", models.CharField(blank=True, help_text="L'auteur du quiz", max_length=50)),
                (
                    "image_background_url",
                    models.URLField(
                        blank=True, help_text="Un lien vers une image pour illustrer le quiz", max_length=500
                    ),
                ),
                ("has_audio", models.BooleanField(default=False, help_text="Le quiz a du contenu audio")),
                ("publish", models.BooleanField(default=False, help_text="Le quiz est prêt à être publié")),
                ("spotlight", models.BooleanField(default=False, help_text="Le quiz est mis en avant")),
                ("created", models.DateField(auto_now_add=True, help_text="La date de création du quiz")),
                ("updated", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizs",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="QuizRelationship",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suivant", "suivant"),
                            ("jumeau", "jumeau"),
                            ("similaire", "similaire"),
                            ("traduction", "traduction"),
                        ],
                        help_text="Le type de relation entre les deux quizs",
                        max_length=50,
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, help_text="La date & heure de la création de la relation"),
                ),
                (
                    "from_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="from_quizs", to="quizs.quiz"
                    ),
                ),
                (
                    "to_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="to_quizs", to="quizs.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(blank=True, default=0)),
                ("created", models.DateField(auto_now_add=True, help_text="La date de création du lien")),
                ("updated", models.DateField(auto_now=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="questions.question")),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizs.quiz")),
            ],
            options={
                "ordering": ["quiz_id", "order"],
                "unique_together": {("quiz", "question")},
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                help_text="Les questions du quiz",
                related_name="quizs",
                through="quizs.QuizQuestion",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="relationships",
            field=models.ManyToManyField(
                help_text="Les quizs similaires ou liés",
                related_name="related_to",
                through="quizs.QuizRelationship",
                to="quizs.quiz",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="Un ou plusieurs tags rattaché au quiz", related_name="quizs", to="tags.tag"
            ),
        ),
    ]
