# Generated by Django 4.0.3 on 2022-03-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quizs", "0001_create_quiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(blank=True, default=0)),
                ("created", models.DateField(auto_now_add=True, help_text="La date de création du lien")),
                ("updated", models.DateField(auto_now=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.question")),
                ("quiz", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quizs.quiz")),
            ],
            options={
                "ordering": ["quiz_id", "order"],
                "unique_together": {("quiz", "question")},
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                help_text="Les questions du quiz",
                related_name="quizs",
                through="quizs.QuizQuestion",
                to="api.question",
            ),
        ),
    ]
