# Generated by Django 4.0.3 on 2022-04-16 10:17

from django.db import migrations


def link_authors(apps, schema_editor):
    Quiz = apps.get_model("quizs", "Quiz")
    User = apps.get_model("users", "User")
    for quiz in Quiz.objects.all():
        author = None
        quiz_author_split = quiz.author.split(" ")
        try:
            author = User.objects.get(first_name=quiz_author_split[0], last_name=quiz_author_split[1])
        except:  # noqa
            try:
                author = User.objects.get(first_name=quiz.author)
            except:  # noqa
                pass
        if author:
            quiz.author_link = author
            quiz.save()


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0002_quiz_author_link"),
    ]

    operations = [
        migrations.RunPython(link_authors),
    ]
