# Generated by Django 4.0.4 on 2022-05-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizs", "0005_alter_quiz_timestamps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="author",
            new_name="author_old",
        ),
        migrations.RenameField(
            model_name="quiz",
            old_name="author_link",
            new_name="author",
        ),
    ]
