# Generated by Django 4.0.4 on 2022-05-04 21:12

import uuid

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizs", "0006_rename_quiz_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalQuiz",
            fields=[
                ("id", models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                ("slug", models.SlugField(verbose_name="Fragment d'URL")),
                ("introduction", ckeditor.fields.RichTextField(blank=True, verbose_name="Introduction")),
                (
                    "conclusion",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Inclure des pistes pour aller plus loin", verbose_name="Conclusion"
                    ),
                ),
                ("difficulty_average", models.FloatField(default=0, verbose_name="Difficulté moyenne")),
                (
                    "language",
                    models.CharField(
                        choices=[("Français", "Français"), ("English", "English")],
                        default="Français",
                        max_length=50,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "image_background_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Lien vers une image pour illustrer le quiz"
                    ),
                ),
                ("has_audio", models.BooleanField(default=False, verbose_name="Contenu audio ?")),
                ("publish", models.BooleanField(default=False, verbose_name="Prêt à être publié ?")),
                ("spotlight", models.BooleanField(default=False, verbose_name="Mise en avant ?")),
                ("created", models.DateTimeField(blank=True, editable=False, verbose_name="Date de création")),
                (
                    "updated",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Date de dernière modification"),
                ),
                (
                    "history_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Quiz",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
