# https://github.com/pascalgn/automerge-action
name: automerge
on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "{pullRequest.title} - #{pullRequest.number}"
          MERGE_FORKS: false
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 30000
