name: cron_export_contributions_to_notion

# Controls when the action will run. 
on:
  schedule:
    # Every 6 hours (4 times a day: 00:45, 06:45, 12:45, 18:45)
    - cron: '45 */6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export_contributions_to_notion:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X "GET" "${{ secrets.BACKEND_URL }}/actions/export-contributions-to-notion?token=${{ secrets.CRON_GITHUB_ACTION_SECRET }}"
