name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"style","section":"Technical","hidden":false},
              {"type":"docs","section":"Technical","hidden":false},
              {"type":"test","section":"Technical","hidden":false},
              {"type":"chore","section":"Technical","hidden":false},
              {"type":"refactor","section":"Technical","hidden":false}
            ]
